apiVersion: apps/v1
kind: Deployment
metadata:
    name: runner-pod-npu-scheduler
    namespace: kube-system
    labels:
        component: runner-pod-npu-scheduler
spec:
    replicas: 1
    selector:
        matchLabels:
            component: runner-pod-npu-scheduler
    template:
        metadata:
            labels:
                component: runner-pod-npu-scheduler
        spec:
            serviceAccountName: runner-pod-npu-scheduler
            imagePullSecrets:
              - name: huawei-swr-image-pull-secret-model-gy
            containers:
                - name: scheduler
                  image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/scheduler-plugins:4aea04ec881bf416a1345f3c669440c1fd5e88a3
                  imagePullPolicy: Always
                  command:
                      - /bin/kube-scheduler
                      - --config=/etc/kubernetes/scheduler-config.yaml
                      - --v=3
                  volumeMounts:
                      - name: config
                        mountPath: /etc/kubernetes
            volumes:
                - name: config
                  configMap:
                      name: runner-pod-npu-scheduler-config
